GET http://localhost:3001/todos

// stacks the arrays or roots

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "watch the throne"
}

###

DELETE http://localhost:3001/todo/delete/614c3484b07764fc02a9c180

###

PUT http://localhost:3001/todo/complete/614c302ab07764fc02a9c171